[platformio]
extra_configs = secrets.ini
default_envs = esp32-wroom-32e-dev

; ============================================
;  ENV COMMUN À TOUS LES ESP32
;  (s'applique à TOUTES les sections [env:...])
; ============================================
[env]
upload_speed  = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

board_upload.flash_size = 8MB
board_build.partitions  = partitions.csv

build_flags =
  -Os
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -DCORE_DEBUG_LEVEL=0
  -DFORCE_DEVKEY_FROM_BUILD=1
  -DHAVE_MQTT_CLIENT_CERT
  ; --- PATCH: forcer l’include des libs Network ---
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src"
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Networking/src"
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/NetworkClientSecure/src"

build_unflags = -flto
lib_ldf_mode = deep+

monitor_rts = 0
monitor_dtr = 0

lib_deps =
  h2zero/NimBLE-Arduino@2.3.6
  bblanchon/ArduinoJson@^6.21.3
  adafruit/Adafruit AHTX0@^2.0.5
  adafruit/Adafruit NeoPixel@^1.12.3
  knolleary/PubSubClient@^2.8
  https://github.com/adafruit/ENS160_driver

extra_scripts =
  pre:scripts/pre_build_devkey.py
  post:scripts/post_upload_register.py

board_build.embed_txtfiles =
  src/certs/ca_rezoleo.pem
  src/certs/hivemq_ca.pem

; ⚠️ commun aux deux (clé d’usine + device key)
custom_device_key_b64 = FlR/mc0zM8UX6l+eqyMV71dPOHWQiO14GmoJrpqI/Zk=
custom_factory_token  = kB1qnv5/b7y7gzYAgs8+3Uey/exyvbsJ43BKzOe5Swg=

; ============================================
;  ENV  DEV
; ============================================
[env:esp32-wroom-32e-dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32dev
framework = arduino

; utilisé par post_upload_register.py
custom_api_url = https://breezly-backendweb.onrender.com

build_flags =
  ${env.build_flags}
  -DBREEZLY_DEV

; ============================================
;  ENV  PROD
; ============================================
[env:esp32-wroom-32e-prod]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32dev
framework = arduino

custom_api_url = https://breezly-backend.onrender.com

build_flags =
  ${env.build_flags}
  -DBREEZLY_PROD
