[env:esp32-wroom-32e-usb]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32dev
framework = arduino
upload_speed  = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_upload.flash_size = 8MB
board_build.partitions  = partitions.csv
build_flags =
  -Os
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -DCORE_DEBUG_LEVEL=0
  -DHAVE_MQTT_CLIENT_CERT
  ; --- PATCH: forcer l’include des libs Network ---
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src"
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Networking/src"
  -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/NetworkClientSecure/src"

build_unflags = -flto
lib_ldf_mode = deep+
monitor_rts = 0 
monitor_dtr = 0 
lib_deps =
  h2zero/NimBLE-Arduino@2.3.6
  bblanchon/ArduinoJson@^6.21.3
  adafruit/Adafruit AHTX0@^2.0.5
  adafruit/Adafruit NeoPixel@^1.12.3
  knolleary/PubSubClient@^2.8
  https://github.com/adafruit/ENS160_driver

extra_scripts = post:scripts/post_upload_register.py
board_build.embed_txtfiles =
  src/certs/ca_rezoleo.pem       ; CA EAP (entreprise Wi-Fi)
  src/certs/hivemq_ca.pem        ; CA du broker MQTT
  ;src/certs/client_cert.pem      ; (optionnel, mTLS)
  ;src/certs/client_key.pem       ; (optionnel, mTLS)
