; Options communes à tous les envs (dev, prod, usb)
[env]
; Clé HMAC 32 octets en base64
custom_device_key_b64 = FlR/mc0zM8UX6l+eqyMV71dPOHWQiO14GmoJrpqI/Zk=
custom_factory_token  = kB1qnv5/b7y7gzYAgs8+3Uey/exyvbsJ43BKzOe5Swg=
custom_mqtt_user      = admin
custom_mqtt_pass      = 26052004Sg

; Overrides spécifiques à l'env USB si besoin
[env:esp32-wroom-32e-usb]
custom_api_url_prod   = https://breezly-backend.onrender.com
custom_api_url_dev    = https://breezly-backendweb.onrender.com
