[env:esp32-wroom-32e-usb]
; ⚠️ Clé HMAC 32 octets en base64
custom_device_key_b64 = FlR/mc0zM8UX6l+eqyMV71dPOHWQiO14GmoJrpqI/Zk=

; Ton token d’usine pour l’API interne
custom_factory_token  = kB1qnv5/b7y7gzYAgs8+3Uey/exyvbsJ43BKzOe5Swg=

; URL backend
custom_api_url        = https://breezly-backend.onrender.com
